name: "💡 Feature Request"
description: Got a cool idea? Suggest it here
title: "💡 [FEATURE] - <title>"
labels: ["feature"]
body:
  - type: checkboxes
    id: terms
    attributes:
      label: Idea Contribution
      description: Before you open an issue, please check if a similar issue already exists or has been closed before.
      options:
        - label: I have read all the feature request issues.
          required: true
  - type: textarea
    id: whats-your-idea
    attributes:
      label: Explain feature request
      description: Is your feature request related to a problem? Please describe.
      placeholder: Provide a clear and concise description of the problem. For example, "I consistently encounter frustration when..."
    validations:
      required: false
  - type: textarea
    id: whats-your-solution
    attributes:
      label: Explain your solution
      description: Could you outline the solution you envision?
      placeholder: Give a clear and concise description of the desired outcome.
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: Any alternative approaches/features
      description: Have you considered any alternative approaches or features?
      placeholder: Provide a clear and concise description of any other solutions or functionalities you've contemplated.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional Context
      description: Include any extra information or visuals that may be relevant to the feature request.
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: Record
      options:
        - label: I'm a GSSOC'24 contributor
        - label: I'm interested in working on this issue
